### ISSUE TITLE
400 Error: request size did not match content length

### ISSUE THREAD

**Issue by dimitar9** [azat-co/practicalnode#7]
http://stackoverflow.com/questions/26922125/node-js-post-causes-error

 0 down vote favorite
	

I am running this app. the only change is twitter consumer key and secret I made in app.js file

I can run this app and sign-in with twitter. But when I try to post an article it causes error.

Connect
400 Error: request size did not match content length

    at makeError (/home/myname/Documents/nodejs/practicalnode/ch7/blog-express/node_modules/body-parser/node_modules/raw-body/index.js:136:15)
    at IncomingMessage.onEnd (/home/myname/Documents/nodejs/practicalnode/ch7/blog-express/node_modules/body-parser/node_modules/raw-body/index.js:106:13)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:938:16
    at process._tickCallback (node.js:419:13)

What should I check?what could be wrong. thanks

**Comment by azat-co** [comment]
is this still relevant? 
what is your post looks like?
